#!/bin/sh
set -e

if [ -f "$XDEBUG_TARGET" ]; then
	rm $XDEBUG_TARGET
fi

if [ "$PHP_XDEBUG_ENABLED" = "1" ]; then
	ln -s /usr/local/xdebug-extension.ini $XDEBUG_TARGET
fi

exec docker-php-entrypoint "$@"
